# -*- coding: utf-8 -*-
"""Generate data/diagnostics/subsystem_labels_en.json (English names for canonical symptom subsystems).

canonical_symptoms.json names each symptom's subsystems in Turkish only. The
copilot shows a subsystem as an "area to inspect" row; in an English answer it
needs an English name. This file is a plain label translation: one Turkish
label -> one English label, no new subsystem, value or claim. The unit tests
check that every subsystem label of every symptom has an entry.
"""
import json
import os
import re

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))  # run from repo root

P = "data/diagnostics/subsystem_labels_en.json"

L = {
 "Ateşleme & Marş Sistemi": "Ignition & starting system",
 "Yakıt Besleme Sistemi": "Fuel supply system",
 "Akü & Elektrik Besleme": "Battery & electrical supply",
 "Hava Emiş & Turbo Sistemi": "Air intake & turbo system",
 "Yakıt Enjeksiyon Sistemi": "Fuel injection system",
 "EGR & Emisyon": "EGR & emissions",
 "Soğutma Sistemi": "Cooling system",
 "Termostat & Radyatör": "Thermostat & radiator",
 "Silindir Kapak Contası": "Cylinder head gasket",
 "Ateşleme Sistemi (Buji/Bobin)": "Ignition system (plugs/coils)",
 "Yakıt Enjektörleri": "Fuel injectors",
 "Vaküm Kaçağı": "Vacuum leak",
 "Motor Yağlama Sistemi": "Engine lubrication system",
 "Yağ Pompası & Filtresi": "Oil pump & filter",
 "Yatak & Krank": "Bearings & crankshaft",
 "Deniz Emniyet & Ateşleme Kilidi": "Marine safety & ignition interlock",
 "Nötr Güvenlik Anahtarı": "Neutral safety switch",
 "Akü Ana Şalter": "Battery main switch",
 "Egzoz Emisyon & DPF Sistemi": "Exhaust emissions & DPF system",
 "Diferansiyel Basınç Sensörü": "Differential pressure sensor",
 "EGT Sensörleri": "EGT sensors",
 "SCR & AdBlue Dozaj Sistemi": "SCR & AdBlue dosing system",
 "NOx Sensörleri": "NOx sensors",
 "DEF Isıtıcı & Pompa": "DEF heater & pump",
 "Otomatik Şanzıman / TCU": "Automatic transmission / TCU",
 "Tork Konvertörü": "Torque converter",
 "Vana Gövdesi & Solenoidler": "Valve body & solenoids",
 "Fren Sistemi & ABS/ESP": "Brake system & ABS/ESP",
 "Tekerlek Hız Sensörleri": "Wheel speed sensors",
 "Direksiyon Açı Sensörü": "Steering angle sensor",
 "Aşırı Doldurma & Turbo Şarj": "Boost & turbocharging",
 "İntercooler & Hortumlar": "Intercooler & hoses",
 "Wastegate / VNT Aktüatörü": "Wastegate / VNT actuator",
 "Wastegate Solenoidi": "Wastegate solenoid",
 "MAP Sensörü": "MAP sensor",
 "Akü & Şarj Sistemi": "Battery & charging system",
 "Gövde Kontrol Modülü (BCM)": "Body control module (BCM)",
 "Alternatör & Diyot Tablası": "Alternator & rectifier",
 "CAN Bus & Ağ İletişimi": "CAN bus & network communication",
 "Ağ Ağ Geçidi (Gateway)": "Network gateway",
 "Sonlandırma Dirençleri": "Terminating resistors",
 "Yakıt Besleme & Enjeksiyon": "Fuel supply & injection",
 "Yüksek Basınç Pompası": "High-pressure pump",
 "Basınç Regülatör Valfi": "Pressure regulator valve",
 "Dizel Ön Isıtma Sistemi": "Diesel pre-heating system",
 "Kızdırma Rölesi": "Glow plug relay",
 "Motor Sıcaklık Sensörü": "Engine temperature sensor",
 "Pnömatik Fren Sistemi (EBS)": "Pneumatic brake system (EBS)",
 "Fren Hava Kompresörü": "Brake air compressor",
 "Dört Devre Emniyet Valfi": "Four-circuit protection valve",
 "Deniz Motoru Soğutma Sistemi": "Marine engine cooling system",
 "Ham Su Pompası (Lastik Çark)": "Raw water pump (impeller)",
 "Egzoz Karışım Dirseği": "Exhaust mixing elbow",
 "Yüksek Gerilim Güvenlik Sistemi": "High-voltage safety system",
 "HV Kilitleme Döngüsü (HVIL)": "HV interlock loop (HVIL)",
 "Batarya Yönetim Sistemi (BMS)": "Battery management system (BMS)",
 "Ham Su Soğutma Pompası": "Raw water cooling pump",
 "Isı Eşleyici": "Heat exchanger",
 "Gövde Titreşim İzleme": "Hull vibration monitoring",
 "Hava Soğutucu (İntercooler)": "Charge air cooler (intercooler)",
 "Turboşarj Sistemi": "Turbocharger system",
 "EGT Sıcaklık İzleme": "EGT monitoring",
 "Kompresör Hava Emiş Filtresi": "Compressor air intake filter",
 "Turboşarj Kompresör Pervanesi": "Turbocharger compressor wheel",
 "Deniz Common Rail Enjektörler": "Marine common rail injectors",
 "Egzoz Gazı Sıcaklık Sensörleri (EGT)": "Exhaust gas temperature sensors (EGT)",
 "Turboşarj Rulman Yatağı": "Turbocharger bearing",
 "Wastegate Tahliye Mekanizması": "Wastegate mechanism",
 "Pervane & Şaft Sistemi": "Propeller & shaft system",
 "Hız Göstergesi (STW vs SOG)": "Speed log (STW vs SOG)",
 "Dümen Pompası & Silindiri": "Steering pump & cylinder",
 "Dümen Açı Geri Bildirim Sensörü (PGN 127245)": "Rudder angle feedback sensor (PGN 127245)",
 "Sintine Seviye Sensörü (PGN 127505)": "Bilge level sensor (PGN 127505)",
 "Sintine Pompaları & Flatör": "Bilge pumps & float switch",
 "Isı Eşleyici Boru Demeti": "Heat exchanger tube bundle",
 "Termostat Devresi": "Thermostat circuit",
 "Ters Osmoz Su Yapıcı (PGN 130567)": "Reverse osmosis watermaker (PGN 130567)",
 "Egzoz Karışım Dirseği (Mixing Elbow)": "Exhaust mixing elbow",
 "Ham Su Tahliye Enjeksiyonu": "Raw water exhaust injection",
 "Jeneratör Elektronik Regülatörü (Governor)": "Generator electronic governor",
 "Yakıt Pompası & Aktüatörü": "Fuel pump & actuator",
 "Sahil Bağlantı Panosu": "Shore power panel",
 "Galvanik İzolatör": "Galvanic isolator",
 "Kaçak Akım Rölesi (RCD)": "Residual current device (RCD)",
 "Ön Yakıt Separatörü (Racor/Separ)": "Primary fuel separator (Racor/Separ)",
 "Su Tespit Probu (WIF)": "Water-in-fuel probe (WIF)",
 "Dümen Pompası (Helm Pump)": "Helm pump",
 "Silindir & Havalandırma Nipeline": "Cylinder & bleed nipple",
 "HVIL Döngüsü": "HVIL loop",
 "MSD Servis Soketi": "MSD service disconnect",
 "İnvertör / BMS Kapak Sensörleri": "Inverter / BMS cover switches",
 "BMS Ana Pozitif/Negatif Kontaktörleri": "BMS main positive/negative contactors",
 "Ön Şarj Devresi": "Pre-charge circuit",
 "Batarya Modülleri": "Battery modules",
 "Hücre Dengeleme Devresi (ASIC)": "Cell balancing circuit (ASIC)",
 "Batarya Termal Sensörleri": "Battery thermal sensors",
 "Acil Tahliye / Duman Sensörü": "Vent / smoke sensor",
 "OBC (Dahili Şarj Cihazı)": "OBC (on-board charger)",
 "Şarj Portu Solenoid Kilidi": "Charge port solenoid lock",
 "İnvertör Güç Modülü (IGBT/SiC)": "Inverter power module (IGBT/SiC)",
 "Rotor Konum Sensörü (Resolver)": "Rotor position sensor (resolver)",
 "DC-DC Dönüştürücü": "DC-DC converter",
 "12V Yardımcı Akü": "12V auxiliary battery",
 "12V Güç Dağıtım Modülü": "12V power distribution module",
 "BMS Ön Şarj Rölesi": "BMS pre-charge relay",
 "Ön Şarj Direnci": "Pre-charge resistor",
 "İnvertör Giriş Kapasitörleri": "Inverter input capacitors",
 "BMS Şarj Akımı Sınırlandırıcısı": "BMS charge current limiter",
 "Elektronik Fren Servosu (iBooster)": "Electronic brake booster (iBooster)",
 "Pnömatik Kompresör Başlığı": "Air compressor head",
 "Regülatör (Governor) Valfi": "Governor valve",
 "Hava Kurutucu (APU/EAC)": "Air dryer (APU/EAC)",
 "Tahliye Isıtıcı Rezistansı": "Purge heater element",
 "Hava Tankları": "Air tanks",
 "Kurutucu Desikant Kartuşu": "Dryer desiccant cartridge",
 "Hidrodinamik Retarder / İntarder": "Hydrodynamic retarder / intarder",
 "Soğutma Suyu Oransal Valfi": "Coolant proportional valve",
 "Bahar Fren Körüğü (Kombine Körük)": "Spring brake chamber (combination chamber)",
 "El Freni Kumanda Valfi": "Park brake control valve",
 "ISO 7638 7-Pin Soket/Kablo": "ISO 7638 7-pin socket/cable",
 "Dorse EBS Modülatörü": "Trailer EBS modulator",
 "AdBlue Dozaj Enjektörü": "AdBlue dosing injector",
 "Dozaj Pompası Basınç Sensörü": "Dosing pump pressure sensor",
 "VGT Elektronik / Pnömatik Aktüatörü": "VGT electronic / pneumatic actuator",
 "Turbo Nozul Segmanı": "Turbo nozzle ring",
 "Karter Havalandırma Filtresi (CCV)": "Crankcase ventilation filter (CCV)",
 "Piston Segmanları & Gömlekler": "Piston rings & liners",
 "Common Rail Enjektör O-Ringleri": "Common rail injector o-rings",
 "Tandem / Yüksek Basınç Pompası Keçesi": "Tandem / high-pressure pump seal",
 "Motor Kontrol Ünitesi (ECM)": "Engine control module (ECM)",
 "SCR Emisyon İzleme": "SCR emissions monitoring",
 "Hava Emiş Kaçağı": "Intake air leak",
 "Yakıt Basıncı": "Fuel pressure",
 "Krank Mili Pozisyon Sensörü": "Crankshaft position sensor",
 "MAF Sensörü": "MAF sensor",
 "Emme Manifoldu Vakum Hatları": "Intake manifold vacuum lines",
 "Yakıt Pompası": "Fuel pump",
 "Yakıt Enjektörleri (Damlatan)": "Fuel injectors (dripping)",
 "EVAP Tahliye Valfi": "EVAP purge valve",
 "O2 Sensörü": "O2 sensor",
 "Bank 2 Manifold Contası": "Bank 2 manifold gasket",
 "Bank 2 Enjektörleri": "Bank 2 injectors",
 "Bank 2 Lambda Sensörü": "Bank 2 lambda sensor",
 "Yüksek Basınç Regülatör Valfi (PCV)": "High-pressure control valve (PCV)",
 "Basınç Sensörü": "Pressure sensor",
 "Hava Filtresi Kutusu & Giriş Kanalı": "Air box & intake duct",
 "Emme Manifoldu Vakum Portu": "Intake manifold vacuum port",
 "Elektronik Gaz Kelebeği Motoru": "Electronic throttle motor",
 "TPS Çift Potansiyometresi": "TPS dual potentiometer",
 "IAT Sensörü": "IAT sensor",
 "Sensör Kablo Tesisatı": "Sensor wiring",
 "Triger Kayışı / Zinciri": "Timing belt / chain",
 "Krank Sensörü": "Crank sensor",
 "Eksantrik Sensörü": "Camshaft sensor",
 "VVT / Vanos Solenoid Valfi": "VVT / Vanos solenoid valve",
 "Eksantrik Faz Dişlisi": "Cam phaser",
 "Motor Yağ Kanalı": "Engine oil passage",
 "Krank Pozisyon Sensörü (CKP)": "Crankshaft position sensor (CKP)",
 "Volan Dişli Halkası": "Flywheel tone ring",
 "Vuruntu Sensörü (Piezoseramik)": "Knock sensor (piezo-ceramic)",
 "Sensör Sıkma Torku": "Sensor tightening torque",
 "Soğutma Suyu Termostatı": "Coolant thermostat",
 "Motor Sıcaklık Sensörü (ECT)": "Engine coolant temperature sensor (ECT)",
 "Radyatör Fan Motoru": "Radiator fan motor",
 "Fan Kontrol Rölesi / Direnci / PWM Modülü": "Fan control relay / resistor / PWM module",
 "Yağ Soğutucu Eşleyicisi": "Oil cooler",
 "Yağ Sıcaklık Sensörü": "Oil temperature sensor",
 "Katalitik Konvertör": "Catalytic converter",
 "Arka O2 Sensörü (Lambda 2)": "Rear O2 sensor (lambda 2)",
 "Bank 2 Katalitik Konvertör": "Bank 2 catalytic converter",
 "Bank 2 Arka Lambda": "Bank 2 rear lambda",
 "Depo Dolum Kapağı": "Fuel filler cap",
 "EVAP Kanister & Hortumlar": "EVAP canister & hoses",
 "Tahliye / Havalandırma Valfi": "Purge / vent valve",
 "Kanister Tahliye Valfi (Purge Solenoid)": "Canister purge valve (purge solenoid)",
 "Emme Manifoldu": "Intake manifold",
 "Ön Lambda Sensörü Isıtıcı Rezistansı": "Front lambda sensor heater element",
 "Isıtıcı Sigorta & Rölesi": "Heater fuse & relay",
 "Arka Lambda Sensörü Isıtıcı Rezistansı": "Rear lambda sensor heater element",
 "EGR Valfi": "EGR valve",
 "EGR Pozisyon Sensörü": "EGR position sensor",
 "EGR Soğutucusu": "EGR cooler",
 "EGR Gaz Geçiş Kanalları": "EGR gas passages",
 "Tork Konvertör Kilidi Solenoidi (TCC)": "Torque converter clutch solenoid (TCC)",
 "Konvertör Debriyaj Balatası": "Converter clutch lining",
 "TCC Solenoid Valfi": "TCC solenoid valve",
 "Vana Gövdesi Kilit Sürgüsü": "Valve body lock-up valve",
 "Vana Gövdesi Vites Solenoidi A": "Valve body shift solenoid A",
 "Şanzıman Dahili Kablo Tesisatı": "Transmission internal wiring",
 "Şanzıman Yağ Soğutucusu (Termostat)": "Transmission oil cooler (thermostat)",
 "TFT Sıcaklık Sensörü": "TFT temperature sensor",
 "Transfer Kutusu Vites Motoru": "Transfer case shift motor",
 "Konum Kodlayıcı Sensör": "Position encoder sensor",
 "Sol Ön ABS Sensörü": "Front left ABS sensor",
 "Poyra Manyetik Segmanı (Encoder Ring)": "Hub magnetic encoder ring",
 "ABS Hidrolik Pompa Motoru": "ABS hydraulic pump motor",
 "ABS Motor Rölesi & Güç Sigortası": "ABS motor relay & main fuse",
 "Direksiyon Açı Sensörü (SAS)": "Steering angle sensor (SAS)",
 "Sargı / Döner Kumanda Modülü": "Clockspring / steering column module",
 "ESP Ataletsel Sensör Kümesi (IMU)": "ESP inertial sensor cluster (IMU)",
 "Orta Konsol Montaj Yuvası": "Centre console mounting",
 "Arka Fren Kaliper Motorları": "Rear brake caliper motors",
 "EPB Kontrol Modülü": "EPB control module",
 "Süspansiyon Hava Kompresörü": "Air suspension compressor",
 "Hava Körükleri & Valf Bloğu": "Air springs & valve block",
 "Direksiyon Zembereği (Clockspring)": "Clockspring",
 "Sürücü Hava Yastığı Modülü": "Driver airbag module",
 "Alternatör Dahili Voltaj Regülatörü (Konjektör)": "Alternator internal voltage regulator",
 "Akü": "Battery",
 "Marş Motoru Rölesi": "Starter relay",
 "Kontak Termiği / Start Butonu": "Ignition switch / start button",
 "Marş Selenoidi": "Starter solenoid",
 "Klima Gaz Basınç Sensörü": "A/C refrigerant pressure sensor",
 "Klima Manyetik Kavraması": "A/C compressor clutch",
 "Kondenser & Evaporatör": "Condenser & evaporator",
 "Klape Yönlendirme Motoru (Blend Actuator)": "Blend door actuator",
 "Klima Kontrol Paneli": "Climate control panel",
 "İmmobilizer Okuyucu Anten Bobini": "Immobiliser reader coil",
 "Anahtar RFID Çipi": "Key RFID chip",
 "Gösterge Paneli / BCM": "Instrument cluster / BCM",
 "Enjektör Sürücü Devresi (ECM)": "Injector driver circuit (ECM)",
 "Bobin Tetikleme Sinyali": "Coil trigger signal",
 "Sağ Ön ABS Sensörü": "Front right ABS sensor",
 "Poyra Manyetik Segmanı": "Hub magnetic ring",
 "Sol Arka ABS Sensörü": "Rear left ABS sensor",
 "Sağ Arka ABS Sensörü": "Rear right ABS sensor",
 "Sol Ön TPMS Sensörü (RF 433MHz)": "Front left TPMS sensor (RF 433MHz)",
 "Sağ Ön TPMS Sensörü (RF 433MHz)": "Front right TPMS sensor (RF 433MHz)",
 "Sol Arka TPMS Sensörü (RF 433MHz)": "Rear left TPMS sensor (RF 433MHz)",
 "Sağ Arka TPMS Sensörü (RF 433MHz)": "Rear right TPMS sensor (RF 433MHz)",
 "Giriş/Çıkış Hız Sensörleri (ISS/OSS)": "Input/output speed sensors (ISS/OSS)",
 "Vana Gövdesi Solenoid B": "Valve body solenoid B",
 "TCU Sürücü Katı": "TCU driver stage",
 "Vana Gövdesi Solenoid C": "Valve body solenoid C",
 "Elektronik Basınç Kontrol Solenoidi (EPC)": "Electronic pressure control solenoid (EPC)",
 "Ana Hat Basınç Regülatörü": "Main line pressure regulator",
 "BMS Hücre Gerilim Ölçüm Devresi (CSC)": "BMS cell voltage sensing circuit (CSC)",
 "Hücre Dengeleme Dirençleri": "Cell balancing resistors",
 "Batarya Soğutma Pompası (BLDC)": "Battery coolant pump (BLDC)",
 "Batarya Soğutma Sıvısı Devresi": "Battery coolant circuit",
 "EVSE Şarj İletişim Kontrolörü (EVCC)": "EV charging communication controller (EVCC)",
 "HomePlug Green PHY Modemi": "HomePlug Green PHY modem",
 "Ayak Fren Ventili (Treadle Valve)": "Foot brake valve (treadle valve)",
 "Fren Devre 1 & 2": "Brake circuits 1 & 2",
 "J1939 CAN Backbone Kablo Demeti": "J1939 CAN backbone harness",
 "120 Ohm Sonlandırma Dirençleri": "120 Ohm terminating resistors",
 "SCR Katalizörü": "SCR catalyst",
 "Giriş/Çıkış NOx Sensörleri": "Inlet/outlet NOx sensors",
 "Soğutma Sıvısı Seviye Probu": "Coolant level probe",
 "Genleşme Tankı": "Expansion tank",
 "Emme Eksantrik Sensörü": "Intake camshaft sensor",
 "Sensör Kablo Demeti": "Sensor harness",
 "Ön Lambda Sensörü (Zirkonya/Geniş Bant)": "Front lambda sensor (zirconia/wideband)",
 "Depo Havalandırma Hortumları": "Tank vent hoses",
 "Kanister Gövdesi": "Canister body",
 "Fren Pedalı Konum Anahtarı (Çift Kontak)": "Brake pedal position switch (dual contact)",
 "Fren Lambaları": "Brake lamps",
 "Debriyaj Pedal Müşürü": "Clutch pedal switch",
 "Marş Güvenlik Kilidi": "Start interlock",
 "Dış Sıcaklık Sensörü (Ayna/Tampon)": "Ambient temperature sensor (mirror/bumper)",
 "Gösterge & Klima Paneli": "Instrument & climate panel",
 "Yakıt Pompası Kontrol Modülü (FPDM)": "Fuel pump driver module (FPDM)",
 "Düşük Basınç Depo İçi Pompa": "Low-pressure in-tank pump",
}

# numbered families
FAMILY = [
 (r"^(\d+)\. Silindir Buji & Bobin$", "Cylinder {n} plug & coil"),
 (r"^(\d+)\. Silindir Enjektörü$", "Cylinder {n} injector"),
 (r"^(\d+)\. Silindir Kompresyon$", "Cylinder {n} compression"),
 (r"^(\d+)\. Silindir Yakıt Enjektörü$", "Cylinder {n} fuel injector"),
 (r"^(\d+)\. Silindir Ateşleme Bobini$", "Cylinder {n} ignition coil"),
 (r"^(\d+)\. Vites Debriyaj Paketi$", "Gear {n} clutch pack"),
]

with open("data/diagnostics/canonical_symptoms.json", encoding="utf-8") as fh:
    symptoms = json.load(fh)["symptoms"]
labels = {}
for rec in symptoms.values():
    for label in rec.get("subsystems") or []:
        if label in labels:
            continue
        en = L.get(label)
        for pattern, template in FAMILY:
            m = re.match(pattern, label)
            if en is None and m:
                en = template.format(n=m.group(1))
        if en is None:
            raise SystemExit(f"no English label for {label!r}")
        labels[label] = en

out = {
 "schema_version": 1,
 "title": "English names for canonical symptom subsystems",
 "_rule": ("Plain translation of canonical_symptoms.json subsystem labels (Turkish -> English) for "
           "English copilot answers. No new subsystem, value or claim."),
 "labels": labels,
 "provenance": [{
   "provenance_id": "prv-subsystem-labels-en",
   "target": {"record_id": "subsystem_labels_en", "field": "labels"},
   "activity": "translate_labels",
   "activity_version": "copilot-labels-1",
   "agent": {"type": "curator", "id": "ucanlab-copilot-curation", "role": "author"},
   "source": {"title": "canonical_symptoms.json subsystems (Turkish labels)",
              "path": "data/diagnostics/canonical_symptoms.json", "type": "internal_kb"},
   "transform": {"rule_id": "label-translation"},
   "confidence": "single_source",
 }],
}
with open(P, "w", encoding="utf-8", newline="\n") as fh:
    json.dump(out, fh, ensure_ascii=False, indent=1)
    fh.write("\n")
print(len(labels))
